### ISSUE TITLE
[bug] Wrong keyword name in ReST ":atribute:"

### ISSUE THREAD

**Issue by MatteoCampinoti94** [valentingol/docstripy#12]
Love your tool! My colleagues and I just used it to convert all the docstring in one of our being repositories and it worked great! However, we found some small issue which, while easily solved with regex substitutions, would be great to see solved :)

When converting from a google-style docstring for a class with the `Attributes:` header, the attributes are converted to `:atribute <name>: <text>`, but that is not a common rest docstring keyword.

Instead, we would suggest using the `:ivar <name>: <text>` [as used by Sphinx](https://www.sphinx-doc.org/en/master/usage/domains/python.html#info-field-lists), which is understood by all major IDEs.

**Comment by valentingol** [comment]
Should be fixed in 0.7.1. The section names `:var:`, `:ivar:` and `:cvar: are recognized as attributes sections. When converting a docstring to ReST, the attributes will be under `:var:` section (the module do not distinguish class from instance attributes yet). Please re-open the issue if any problem persists.

**Comment by MatteoCampinoti94** [comment]
Thanks!
